packages:
  - "."

overrides:
  baseline-browser-mapping: 2.11.4

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
